name: wealthwatcher
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  dotenv: ^3.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.18.0
  flutter_bloc: ^8.1.5
  cloud_firestore: ^4.15.10
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
